### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by PlutoAndSaturn** [lucasimi/tda-mapper-python#107]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://tda-mapper-app.streamlit.app/lucasimi/tda-mapper-python/main/app/streamlit_app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by lucasimi** [comment]
Hi, thank you for using the app and for reporting the issue!

The deployment has been restarted from scratch, so if you want you can use the app again now. However, please note that the app is running on a free subscription on Streamlit Cloud and is meant as a demo. If you want to run the app locally on a big dataset, you can download the source code from this repo and run it yourself. These are the steps you need to take:

```
git clone https://github.com/lucasimi/tda-mapper-python.git
cd tda-mapper-python
pip install -r app/requirements.txt
streamlit run app/streamlit_app.py
```

This should be documented more extensively in the readme as well.

As an alternative, you can run your experiments in a jupyter notebook as shown [in the docs](https://tda-mapper.readthedocs.io/en/main/notebooks/circles_online.html).
