### ISSUE TITLE
Unexpected output from core.mapper_connected_components  

### ISSUE THREAD

**Issue by SofiaTorchia** [lucasimi/tda-mapper-python#64]
Running the following lines after the example in readme.md I get a list of twice the size of X.shape[0].
```
cover = CubicalCover(n_intervals=10, overlap_frac=0.65)
clustering = FailSafeClustering(clustering=AgglomerativeClustering(10), verbose=False)

from tdamapper import core
l = core.mapper_connected_components(X,lens,cover,clustering)
```
The first X.shape[0] elements of the output list are -1.
I am using version `tda-mapper==0.2.0`.

**Comment by lucasimi** [comment]
@SofiaTorchia Thank you for reporting the bug.

The issue in the size of the output is due to an incorrect assignment of `labels`:

https://github.com/lucasimi/tda-mapper-python/blob/7cd3814034eea4cb7be8917bfc9b5ee2357ed8d1/src/tdamapper/core.py#L69-L79
